apiVersion: v1
kind: Service
metadata:
  name: nlb-sample-service
  namespace: mongo
  
spec:
  ports:
    - port: 80
      targetPort: 27017
      protocol: TCP
  type: LoadBalancer
  selector:
    app: mongo